[versions]
kotlin = "2.0.20"
compose-plugin = "1.6.11"
versions-plugin = "0.51.0"
dokka-plugin = "1.9.10"
kotlinx-coroutines = "1.6.4"
kotlinx-serialization = "1.6.0"
compose-viewmodel = "2.8.0"
dudrie-commons = "0.7"

[plugins]
compose-core = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka-plugin" }

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
compose-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "compose-viewmodel" }

dudrie-commons-select = { module = "de.github.dudrie:dudrie-commons-select", version.ref = "dudrie-commons" }
